### ISSUE TITLE
Enable ESM and Livepatch after logging in

### ISSUE THREAD

**Issue by powersj** [CanonicalLtd/ubuntu-advantage-client#360] opened 2019-04-11 20:17 UTC
By default when I attach, ESM and livepatch should be enabled if possible.

- ESM should have no problems to enable
- Livepatch should only be enabled if possible. So on Trusty you would enable if the user was on the HWE kernel, but not if they were on the shipping kernel.

**Comment by powersj** [comment] 2019-04-11 20:19
@blackboxsw We should file a bug with the contracts to tell us what to enable or disable by default.

**Comment by OddBloke** [comment] 2019-04-12 16:29
Is this effectively a duplicate of #239?

**Comment by OddBloke** [comment] 2019-04-16 20:36
Closing in favour of #239.

**Closed by OddBloke** 2019-04-16 20:36 UTC
Labels: blocker, bug
