### ISSUE TITLE
Update packaging dependencies: minimum version of apt

### ISSUE THREAD

**Issue by cjohnston1158** [CanonicalLtd/ubuntu-advantage-client#712] opened 2019-08-14 01:03 UTC
Brand new 14.04 VM, did ua attach and I get a traceback

```pytb
cjohnston@ua-client:~$ sudo ua attach <removed>
[sudo] password for cjohnston:
Enabling default service esm
Enabling authenticated repo: https://esm.ubuntu.com
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 397, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 271, in action_attach
    cfg, contract_token, allow_enable=args.auto_enable):
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 264, in request_updated_contract
    allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 220, in process_entitlement_delta
    orig_access, deltas, allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 136, in process_contract_deltas
    if super().process_contract_deltas(orig_access, deltas, allow_enable):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 265, in process_contract_deltas
    self.enable()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 70, in enable
    self.setup_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 221, in setup_apt_config
    keyring_file)
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 136, in add_auth_apt_repo
    add_apt_auth_conf_entry(repo_url, username, password)
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 175, in add_apt_auth_conf_entry
    util.write_file(apt_auth_file, '\n'.join(new_lines), mode=0o600)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 316, in write_file
    with open(filename, 'wb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/auth.conf.d/90ubuntu-advantage'
```

**Comment by OddBloke** [comment] 2019-08-14 13:25
Hey Chris, thanks for the bug report! It looks like you're running 19.5, which suggests you installed from the "UA Client" PPA; could you see if this reproduces with the daily build from https://launchpad.net/~canonical-server/+archive/ubuntu/ua-client-daily, please?

If it does, please paste the output of `find /etc/apt` (or `tree /etc/apt` if you want to install it).

Thanks!

**Comment by cjohnston1158** [comment] 2019-08-14 15:58
cjohnston@ua-client:~$ sudo ua attach ****
Enabling default service esm
Enabling authenticated repo: https://esm.ubuntu.com
Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 365, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 394, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 239, in action_attach
    cfg, contract_token, allow_enable=args.auto_enable):
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 209, in request_updated_contract
    allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/contract.py", line 165, in process_entitlement_delta
    orig_access, deltas, allow_enable=allow_enable)
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 148, in process_contract_deltas
    if super().process_contract_deltas(orig_access, deltas, allow_enable):
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/base.py", line 265, in process_contract_deltas
    self.enable()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 77, in enable
    self.setup_apt_config()
  File "/usr/lib/python3/dist-packages/uaclient/entitlements/repo.py", line 254, in setup_apt_config
    repo_filename, repo_url, token, repo_suites, aptKey, keyring_file
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 159, in add_auth_apt_repo
    add_apt_auth_conf_entry(repo_url, username, password)
  File "/usr/lib/python3/dist-packages/uaclient/apt.py", line 201, in add_apt_auth_conf_entry
    util.write_file(apt_auth_file, '\n'.join(new_lines), mode=0o600)
  File "/usr/lib/python3/dist-packages/uaclient/util.py", line 400, in write_file
    with open(filename, 'wb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/auth.conf.d/90ubuntu-advantage'
cjohnston@ua-client:~$ apt-cache policy ubuntu-advantage-tools
ubuntu-advantage-tools:
  Installed: 19.6~576~git.2cf7ddb~ubuntu14.04.1
  Candidate: 19.6~576~git.2cf7ddb~ubuntu14.04.1
  Version table:
 *** 19.6~576~git.2cf7ddb~ubuntu14.04.1 0
        500 http://ppa.launchpad.net/canonical-server/ua-client-daily/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     10ubuntu0.14.04.3 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
cjohnston@ua-client:~$ find /etc/apt
/etc/apt
/etc/apt/sources.list.d
/etc/apt/sources.list.d/ubuntu-esm-trusty.list
/etc/apt/sources.list.d/canonical-server-ua-client-daily-trusty.list
/etc/apt/preferences.d
/etc/apt/apt.conf.d
/etc/apt/apt.conf.d/70debconf
/etc/apt/apt.conf.d/01autoremove
/etc/apt/apt.conf.d/50unattended-upgrades
/etc/apt/apt.conf.d/10periodic
/etc/apt/apt.conf.d/20apt-esm-hook.conf
/etc/apt/apt.conf.d/20archive
/etc/apt/apt.conf.d/00trustcdrom
/etc/apt/apt.conf.d/00CDMountPoint
/etc/apt/apt.conf.d/20changelog
/etc/apt/apt.conf.d/01autoremove-kernels
/etc/apt/apt.conf.d/00aptitude
/etc/apt/apt.conf.d/99update-notifier
/etc/apt/apt.conf.d/15update-stamp
/etc/apt/apt.conf.d/51ubuntu-advantage-esm
/etc/apt/sources.list
/etc/apt/sources.list.save
/etc/apt/trusted.gpg
/etc/apt/trusted.gpg.d
/etc/apt/trusted.gpg.d/canonical-server-ua-client-daily.gpg~
/etc/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg
/etc/apt/trusted.gpg.d/canonical-server-ua-client-daily.gpg
/etc/apt/sources.list~

**Comment by OddBloke** [comment] 2019-08-14 16:33
OK, so the problem is clear: `/etc/apt/auth.conf.d` doesn't exist. I _suspect_ that this is being caused by a too-old apt; I'm launching an older trusty VM to double check.

**Comment by OddBloke** [comment] 2019-08-14 16:35
As a side-note: a too-old apt is much less likely to be a problem once we're in the archive, because the new `ubuntu-advantage-tools` will be coming from `trusty-updates` which also contains the `apt` that it requires (whereas using the PPA doesn't force you to enable `trusty-updates`).

**Comment by cjohnston1158** [comment] 2019-08-14 16:50
I have trusty-updates enabled. This is a packaging issue in that the package should depend on the required package version. Clearly just having -updates enabled doesn't fix the problem:

cjohnston@ua-client:~$ apt-cache policy apt
apt:
  Installed: 1.0.1ubuntu2.20
  Candidate: 1.0.1ubuntu2.23
  Version table:
     1.0.1ubuntu2.23 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 1.0.1ubuntu2.20 0
        100 /var/lib/dpkg/status
     1.0.1ubuntu2.19 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
     1.0.1ubuntu2 0
        500 http://us.archive.ubuntu.com/ubuntu/ trusty/main amd64 Packages

**Comment by OddBloke** [comment] 2019-08-14 17:24
Having `-updates` enabled and all upgrades applied _would_ fix the problem. I did not say that "just" having it enabled would fix the problem.

**Comment by cjohnston1158** [comment] 2019-08-14 18:06
We've seen a large amount of customers who aren't running with upgrades applied and run into these types of issues. The package dependencies should ensure that the correct packages have been upgraded to meet the needed requirements.

**Comment by OddBloke** [comment] 2019-08-14 18:15
Chris, if we weren't intending to fix this, I would have closed the bug. This version of the client is nowhere near being released, so it's not clear to me why you're pushing on this so much.

**Comment by powersj** [comment] 2019-08-23 16:40
We need to capture the changes made for the Ubuntu packaging bug here as well: https://bugs.launchpad.net/ubuntu/+source/ubuntu-advantage-tools/+bug/1840091

**Comment by OddBloke** [comment] 2019-09-30 16:43
I've just tested, and I believe this is fixed in the daily PPA. Please do reopen if this isn't the case!

**Closed by OddBloke** 2019-09-30 16:43 UTC
Labels: bug

**Comment by panlinux** [comment] 2019-10-16 13:59
Somehow this resurfaced, see https://github.com/CanonicalLtd/ubuntu-advantage-client/issues/845
