### ISSUE TITLE
Unable to get this to work on DigitalOcean's 14.04

### ISSUE THREAD

**Issue by kyrofa** [CanonicalLtd/ubuntu-advantage-client#698] opened 2019-08-02 17:39 UTC
First of all, I added the `canonical-server/ua-client` PPA, and installed `ubuntu-advantage-tools` (side note: DO apparently doesn't seed it). I then grabbed my UA token and ran

    $ sudo ua attach <token>

And this ran successfully.

```
$ sudo ua status
<snip>

SERVICE
cc-eal        none             n/a
cis-audit     none             n/a
esm           entitled         active
fips          none             n/a
fips-updates  none             n/a
livepatch     entitled         n/a
```

However, I can't seem to actually install anything from ESM:

```
$ sudo apt install bash
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  bash-doc
The following packages will be upgraded:
  bash
1 upgraded, 0 newly installed, 0 to remove and 132 not upgraded.
Need to get 576 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://esm.ubuntu.com/ubuntu/ trusty-security/main bash amd64 4.3-7ubuntu1.8 [576 kB]
Err https://esm.ubuntu.com/ubuntu/ trusty-security/main bash amd64 4.3-7ubuntu1.8
  HttpError401
E: Failed to fetch https://esm.ubuntu.com/ubuntu/pool/main/b/bash/bash_4.3-7ubuntu1.8_amd64.deb  HttpError401

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

I did what I did best and whined to @powersj, who expressed surprise at the fact that `/etc/apt/preferences.d/ubuntu-esm-trusty` did not exist. This file only seemed to exist once I disabled ESM, never once I enabled it. I suspect it's just to de-prioritize ESM packages without needing another index update, but the behavior seemed a bit odd so we wanted to call it out.

Any ideas? Happy to try anything out.

**Comment by panlinux** [comment] 2019-08-02 17:46
How did you get a 14.04 droplet created?

**Comment by OddBloke** [comment] 2019-08-02 18:49
@kyrofa Could you paste the output of `find /etc/apt/`, please?

**Comment by OddBloke** [comment] 2019-08-02 18:57
I just attempted to reproduce in a multipass VM locally:

* Launch a trusty VM
* Purge ubuntu-advantage-tools
* Add the PPA and install ubuntu-advantage-tools
* `ua attach <token>`
* `apt update`
* `apt install bash`

This worked as expected for me (unfortunately?).

**Comment by kyrofa** [comment] 2019-08-02 19:00
@OddBloke my pleasure:

```
$ find /etc/apt/
/etc/apt/
/etc/apt/sources.list
/etc/apt/trusted.gpg.d
/etc/apt/trusted.gpg.d/canonical-server-ua-client.gpg
/etc/apt/trusted.gpg.d/canonical-server-ua-client-daily.gpg
/etc/apt/trusted.gpg.d/canonical-server-ua-client.gpg~
/etc/apt/trusted.gpg.d/canonical-server-ua-client-daily.gpg~
/etc/apt/trusted.gpg.d/ubuntu-esm-v2-keyring.gpg
/etc/apt/trusted.gpg
/etc/apt/sources.list.d
/etc/apt/sources.list.d/canonical-server-ua-client-daily-trusty.list
/etc/apt/sources.list.d/ubuntu-esm-trusty.list.save
/etc/apt/sources.list.d/ubuntu-esm-trusty.list
/etc/apt/auth.conf.d
/etc/apt/auth.conf.d/90ubuntu-advantage
/etc/apt/sources.list.save
/etc/apt/apt.conf.d
/etc/apt/apt.conf.d/01autoremove
/etc/apt/apt.conf.d/00CDMountPoint
/etc/apt/apt.conf.d/01autoremove-postgresql
/etc/apt/apt.conf.d/70debconf
/etc/apt/apt.conf.d/20changelog
/etc/apt/apt.conf.d/90cloud-init-pipelining
/etc/apt/apt.conf.d/00aptitude
/etc/apt/apt.conf.d/00trustcdrom
/etc/apt/apt.conf.d/51ubuntu-advantage-esm
/etc/apt/apt.conf.d/10periodic
/etc/apt/apt.conf.d/15update-stamp
/etc/apt/apt.conf.d/01autoremove-kernels
/etc/apt/apt.conf.d/20archive
/etc/apt/apt.conf.d/99update-notifier
/etc/apt/apt.conf.d/50unattended-upgrades
/etc/apt/apt.conf.d/20auto-upgrades
/etc/apt/apt.conf.d/20apt-esm-hook.conf
/etc/apt/preferences.d
/etc/apt/sources.list~
```

**Comment by OddBloke** [comment] 2019-08-02 19:35
Yep, and `/etc/apt/auth.conf.d/90ubuntu-advantage` is the file that we'd expect to see there. For completeness, the diff of our two trees (after switching to the daily PPA myself):

```diff
$ diff -u ours <(sort his)
--- ours	2019-08-02 15:33:02.691142639 -0400
+++ /dev/fd/63	2019-08-02 15:33:05.151142639 -0400
@@ -1,11 +1,16 @@
 /etc/apt/
 /etc/apt/apt.conf.d
+/etc/apt/apt.conf.d/00aptitude
+/etc/apt/apt.conf.d/00CDMountPoint
+/etc/apt/apt.conf.d/00trustcdrom
 /etc/apt/apt.conf.d/01autoremove
 /etc/apt/apt.conf.d/01autoremove-kernels
+/etc/apt/apt.conf.d/01autoremove-postgresql
 /etc/apt/apt.conf.d/10periodic
 /etc/apt/apt.conf.d/15update-stamp
 /etc/apt/apt.conf.d/20apt-esm-hook.conf
 /etc/apt/apt.conf.d/20archive
+/etc/apt/apt.conf.d/20auto-upgrades
 /etc/apt/apt.conf.d/20changelog
 /etc/apt/apt.conf.d/50unattended-upgrades
 /etc/apt/apt.conf.d/51ubuntu-advantage-esm
@@ -16,10 +21,9 @@
 /etc/apt/auth.conf.d/90ubuntu-advantage
 /etc/apt/preferences.d
 /etc/apt/sources.list
+/etc/apt/sources.list~
 /etc/apt/sources.list.d
 /etc/apt/sources.list.d/canonical-server-ua-client-daily-trusty.list
-/etc/apt/sources.list.d/canonical-server-ua-client-trusty.list
-/etc/apt/sources.list.d/canonical-server-ua-client-trusty.list.save
 /etc/apt/sources.list.d/ubuntu-esm-trusty.list
 /etc/apt/sources.list.d/ubuntu-esm-trusty.list.save
 /etc/apt/sources.list.save
```

On my own (not-trusty) droplet, I can confirm that the 00-prefixed files aren't the source of the problem.  Could you paste the contents of `01autoremove-postgresql` and `20auto-upgrades`, just so we can be sure they aren't doing anything that might interfere?

Additionally, it's possible that this is a problem with your token on the backend rather than a DO problem at all; could you launch a trusty system elsewhere and check whether or not ESM works when attaching with the same token?

**Comment by kyrofa** [comment] 2019-08-05 23:36
> Could you paste the contents of 01autoremove-postgresql and 20auto-upgrades, just so we can be sure they aren't doing anything that might interfere?

Of course:

```
$ cat /etc/apt/apt.conf.d/01autoremove-postgresql 
// File installed by postgresql-common. Currently not updated automatically,
// but might be in future releases.
//
// We mark all PostgreSQL packages as NeverAutoRemove because otherwise apt
// would remove the old postgresql-x.y package when the "postgresql" meta
// package changes its dependencies to a new version, rendering the old
// database cluster inaccessible. As access to the cluster might depend on
// other modules (like datatypes), we use a pretty wide pattern here. We might
// tighten this to match only actually used PostgreSQL versions in the future.

APT
{
  NeverAutoRemove
  {
    "^postgresql-";
  };
};
```

```
$ cat /etc/apt/apt.conf.d/20auto-upgrades 
APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";
```

I just now fired up a Trusty lxd instance and I can confirm that the token (and installing the actual updates) works just fine. This seems specific to my DO machine.

**Comment by powersj** [comment] 2019-08-07 15:19
Can you get us the versions of these packages that are install on the system

- apt
- apt-transport-https
- apt-utils
- libapt-inst1.5
- libapt-pkg4.12

**Comment by kyrofa** [comment] 2019-08-07 17:55
- apt: 1.0.1ubuntu2.19
- apt-transport-https: 1.0.1ubuntu2.19
- apt-utils: 1.0.1ubuntu2.19
- libapt-inst1.5: 1.0.1ubuntu2.19
- libapt-pkg4.12: 1.0.1ubuntu2.23

**Comment by powersj** [comment] 2019-08-07 18:14
@julian-klode on trusty are those new enough versions?

**Comment by julian-klode** [comment] 2019-08-07 18:43
No, apt-transport-https is out of date (as are the other apt packages), you'd need 1.0.1ubuntu2.21

**Comment by kyrofa** [comment] 2019-08-07 18:46
```
$ apt-cache policy apt-transport-https
apt-transport-https:
  Installed: 1.0.1ubuntu2.19
  Candidate: 1.0.1ubuntu2.23
  Version table:
     1.0.1ubuntu2.23 0
        500 http://mirrors.digitalocean.com/ubuntu/ trusty-updates/main amd64 Packages
 *** 1.0.1ubuntu2.19 0
        500 http://security.ubuntu.com/ubuntu/ trusty-security/main amd64 Packages
        100 /var/lib/dpkg/status
     1.0.1ubuntu2 0
        500 http://mirrors.digitalocean.com/ubuntu/ trusty/main amd64 Packages
```

Looks like that's in -updates, but this machine only has security updates being automatically installed. This may be a bit of a pickle for machines similarly-configured.

**Comment by powersj** [comment] 2019-08-07 20:49
Can you confirm updating apt fixes the issue? For the old client, the instructions show the need to update and for the new client we should ensure the dependency is listed.

On a fully updated container, apt is version 1.0.1ubuntu2.23, which explains why lxd and multipass were unable to reproduce this.

**Comment by kyrofa** [comment] 2019-08-07 21:02
Confirmed: updating the others didn't seem to change anything, but once I updated `apt-transport-https` (which I did last) things started working.

**Comment by powersj** [comment] 2019-08-23 16:36
This as a duplicate of #712 which we will use to fix the dependency issue. Thanks for catching this and working with us to figure it out.

**Closed by powersj** 2019-08-23 16:36 UTC
