### ISSUE TITLE
DEBUG logging on by default, also logs secrets

### ISSUE THREAD

**Issue by panlinux** [CanonicalLtd/ubuntu-advantage-client#577] opened 2019-06-07 18:01 UTC
After installing `19.5~504~git.9f1326a~ubuntu14.04.1`, I saw that `/var/log/ubuntu-advantage.log` was logging at the `DEBUG` level, even though I never passed `--debug` do the tool:

We get stuff like this:
```
2019-06-07 17:39:55,686 - util.py:(292) [DEBUG]: Writing file: /var/lib/ubuntu-advantage/private/machine-access-support.json
2019-06-07 17:39:55,687 - contract.py:(232) [DEBUG]: Skipping entitlement deltas for "support". No such class
```

But also secrets:
```
2019-06-07 17:39:54,740 - util.py:(193) [DEBUG]: URL [GET] response: https://contracts.canonical.com/v1/resources/livepatch/context/machines/9lalala, headers: Server: nginx/1.15.6
Date: Fri, 07 Jun 2019 17:39:54 GMT
Content-Type: application/json
Content-Length: 539
Connection: close
Vary: Accept-Encoding
X-Trace-Id: oopslol
Strict-Transport-Security: max-age=15724800; includeSubDomains

, data: {'resourceToken': 'mA.....UnA', 'entitlement': {'entitled': True, 'type': 'livepatch', 'affordances': {'kernelFlavors': ['generic', 'lowlatency', 'oem'], 'series': ['trusty', 'xenial', 'bionic'], 'minKernelVersion': '4.4', 'tier': 'stable', 'architectures': ['x86_64']}, 'obligations': {'enableByDefault': True}, 'directives': {'remoteServer': 'https://livepatch.canonical.com', 'caCerts': ''}}}
```

**Comment by panlinux** [comment] 2019-06-07 18:02
Just noted that the config file sets default logging level to debug:
```
root@trusty-ua:~# grep debug /etc/ubuntu-advantage/uaclient.conf 
log_level: debug
```

**Comment by OddBloke** [comment] 2019-06-07 18:12
IMO, debug logging to the log file by default is the right thing to do. We only produce output there when people interact with the tool, so we won't be filling up people's disks (plus we have logrotate configuration). And we have enough moving parts that reproducing issues may be challenging, so not having debug logging for the first time an issue occurs may mean that we can never effectively diagnose it. (And once #479 is addressed, only root will be able to read the log, so we don't need to worry about leaking data.)

On the other hand, this is the obvious behaviour to me and it *isn't* the obvious behaviour for others, so we should make sure we reach a consensus on what the right thing to do is.

(At a bare minimum, we should make sure that whatever behaviour we end up deciding on is correctly documented in `--debug`'s help.)

**Comment by powersj** [comment] 2019-06-07 18:22
I'm marking this blocker and tracking for the current release as I want to get consensus before we ship.

Personally, I also agree that we should be logging to the file with debug output. We do this with cloud-init as another example, and it is very helpful when dealing with issues. However, because there is confusion about this, updating the manpage/help output to explain the --debug needs to be updated.

**Comment by blackboxsw** [comment] 2019-06-07 21:08
Dan landed, #479   I'd say we probably shouldn't redact any content now in the logfile. If that is agreed, we can repurpose this issue and file a branch accoundingly. to unredact secrets

**Comment by OddBloke** [comment] 2019-06-07 21:13
I think this should cover fixing the help for `--debug` and we should have a new issue for unredacting.

**Comment by blackboxsw** [comment] 2019-06-07 22:34
separate unredacting issue #590  landed.
This issue has become a documentation issue for --debug parameter

**Closed** 2019-06-07 23:18 UTC
Labels: blocker, bug
