### ISSUE TITLE
status Description column needs to be dynamically generated from attached machineToken response

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#817] opened 2019-10-09 17:59 UTC
This commit added available resources in https://github.com/CanonicalLtd/ua-contracts/commit/5990871f88e1f97c240b0b8194f708443f2a28d2

**Comment by OddBloke** [comment] 2019-10-09 18:05
Duplicate of #790

**Closed by OddBloke** 2019-10-09 18:05 UTC
