### ISSUE TITLE
Catch tracebacks at cli and suggest that a user file a bug

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#643] opened 2019-06-18 16:34 UTC
Tracebacks at the command line are of limited value to the typical person at the keyboard.
The tracebacks are already recorded in /var/log/ubuntu-advantage.log. 

UA client should catch leaked tracebacks and suggest that the user file an issue so that the client can better provide a sensible error message to the user.

**Comment by panlinux** [comment] 2019-06-24 19:17
We have to be careful to not include `/var/log/ubuntu-advantage.log` in bug reports as that will have credentials.

**Comment by powersj** [comment] 2019-10-23 21:37
I believe we have started capturing tracebacks that make sense (e.g. no internet, dns issue, etc.). I am going to close this and suggest we continue to do that on an as needed basis.

**Comment by OddBloke** [comment] 2019-10-24 14:08
On Wed, Oct 23, 2019 at 02:37:40PM -0700, Joshua Powers wrote:
> I believe we have started capturing tracebacks that make sense (e.g.
> no internet, dns issue, etc.). I am going to close this and suggest we
> continue to do that on an as needed basis.

This issue is intended to cover _all_ tracebacks (i.e. `except
Exception:`), not just the ones caused by exception classes that we have
worked out need special handling.  Currently if we see an unexpected
exception, users will get the full traceback in their console, with no
friendly messaging.

I think we can do better than this without much work, it's just a case
of adding something like:

```py
except Exception:
    with util.disable_log_to_console():
        log.exception('log msg')
    print('user facing msg', file=sys.stderr)
    sys.exit(1)
```

to main_error_handler.

**Closed** 2020-02-21 19:56 UTC
Labels: feature
