### ISSUE TITLE
UA Advantage Register Button results in KeyError: 'accounts'

### ISSUE THREAD

**Issue by jogeo** [CanonicalLtd/ubuntu-advantage-client#840] opened 2019-10-15 18:40 UTC
From the URL below (opened with Firefox), clicked the Register button under "Free for personal use". After the SSO page was shown and accepted a page with KeyError: 'accounts' was displayed. However, after reloading the page the login had completed and commands are shown instructing how to attach and enable a machine.
https://ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/advantage

Please see the attached screen shot.
![20191015_advantage_KeyError_accounts](https://user-images.githubusercontent.com/8658422/66859449-3228f080-ef40-11e9-9434-a59c7729df01.png)

**Comment by marosg42** [comment] 2019-10-15 18:50
I am getting the same error

**Comment by AshleyLai** [comment] 2019-10-15 19:00
I also got the same error.

**Comment by powersj** [comment] 2019-10-15 21:58
@anthonydillon I believe you know about this? can you please update this bug once fixed?

**Comment by gdring2** [comment] 2019-10-15 23:10
I didn't click "register" but "login" then it went to SSO for me to confirm login. 
Then the same screen was shown.

**Comment by anthonydillon** [comment] 2019-10-16 15:24
I believe this is due to having staging SSO cookie set. Either flush your cookies or visit https://ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/logout then go back to https://ubuntu-com-canonical-web-and-design-pr-5769.run.demo.haus/advantage and login. If this issue persists please let me know here.

**Comment by powersj** [comment] 2019-10-16 15:34
Folks, please use the method @anthonydillon above said and let us know!

**Comment by marosg42** [comment] 2019-10-17 07:21
I can confirm logout helped in my case

**Comment by powersj** [comment] 2019-10-17 15:06
Great, closing this then. If you run across the same issue please see anthonydillon's comment above.

**Closed by powersj** 2019-10-17 15:06 UTC
Labels: bug

**Comment by tcuthbert** [comment] 2019-10-18 12:31
I also hit this when attempting to generate a personal use token for the first time today. Attempting the SSO process again unblocked me.
