### ISSUE TITLE
pytest.fixtures currently problematic on trusty

### ISSUE THREAD

**Issue by blackboxsw** [CanonicalLtd/ubuntu-advantage-client#344] opened 2019-04-10 16:59 UTC
test_livepatch would like to use pytes.fixtures to reduce bollierplate config setup

there is an issue with test param ordering on trusty that prevented us from using fixtures properly:
see uaclient/conftest.py

**Comment by OddBloke** [comment] 2019-04-11 16:29
Is this a duplicate of #340?

**Comment by OddBloke** [comment] 2019-04-16 19:54
@blackboxsw It's not clear to me what the problem here is; could you give a bit more detail?

**Comment by OddBloke** [comment] 2019-05-02 19:51
I don't believe we have a fixtures issue on trusty as the tests are working fine there. Let's file new issues for any specific problems we find.

**Closed by OddBloke** 2019-05-02 19:51 UTC
Labels: techdebt
