### ISSUE TITLE
TypeError: datetime.datetime(2020, 9, 30, 0, 0) is not JSON serializable

### ISSUE THREAD

**Issue by cjohnston1158** [CanonicalLtd/ubuntu-advantage-client#795] opened 2019-10-02 21:15 UTC
ubuntu@test2:~⟫ sudo ua attach XXXXXX
This machine is now attached to 'Noble Industrial'.

Traceback (most recent call last):
  File "/usr/bin/ua", line 9, in <module>
    load_entry_point('ubuntu-advantage-tools==19.5', 'console_scripts', 'ubuntu-advantage')()
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 397, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 426, in main
    return args.action(args, cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 281, in action_attach
    action_status(args=None, cfg=cfg)
  File "/usr/lib/python3/dist-packages/uaclient/cli.py", line 341, in action_status
    print(ua_status.format_tabular(cfg.status()))
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 260, in status
    self.write_cache('status-cache', status)
  File "/usr/lib/python3/dist-packages/uaclient/config.py", line 219, in write_cache
    content = json.dumps(content)
  File "/usr/lib/python3.4/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.4/json/encoder.py", line 192, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.4/json/encoder.py", line 250, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: datetime.datetime(2020, 9, 30, 0, 0) is not JSON serializable

apt-cache policy ubuntu-advantage-tools
ubuntu-advantage-tools:
  Installed: 19.5~563~git.722ca83~ubuntu14.04.1
  Candidate: 19.5~563~git.722ca83~ubuntu14.04.1
  Version table:
 *** 19.5~563~git.722ca83~ubuntu14.04.1 0
        500 http://ppa.launchpad.net/canonical-server/ua-client/ubuntu/ trusty/main amd64 Packages
        100 /var/lib/dpkg/status
     10ubuntu0.14.04.4 0
        500 http://mirrors.rcs.alaska.edu/ubuntu/archive/ trusty-updates/main amd64 Packages

**Comment by OddBloke** [comment] 2019-10-02 21:19
Hey Chris, this should be fixed in the daily PPA: https://launchpad.net/~canonical-server/+archive/ubuntu/ua-client-daily

(Closing this out as it's a duplicate of #782 which is itself a duplicate of an older issue. Please reopen if the daily PPA doesn't address it!)

**Closed by OddBloke** 2019-10-02 21:19 UTC
